<?php
namespace controllers\crud\datas;

use Ubiquity\controllers\crud\CRUDDatas;
 /**
  * Class CrudUsersDatas
  */
class CrudUsersDatas extends CRUDDatas{
	public function getFieldNames(string $model) : array{
        return parent::getFieldNames($model); // TODO: Change the autogenerated stub
}

}
